# Generated by Django 5.0.1 on 2024-01-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20, verbose_name='Чат ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Определение')),
                ('description', models.TextField(verbose_name='Формулировка')),
                ('description_math', models.TextField(verbose_name='Формулировка математическая')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_initial', models.BooleanField(default=False, verbose_name='Исходное определение')),
            ],
            options={
                'verbose_name': 'Определение',
                'verbose_name_plural': 'Определения',
            },
        ),
        migrations.CreateModel(
            name='DefinitionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='definitions.definition', verbose_name='Определение')),
                ('used_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_definition', to='definitions.definition', verbose_name='Использованное определение')),
            ],
            options={
                'verbose_name': 'Использование определения',
                'verbose_name_plural': 'Использованиe определений',
            },
        ),
        migrations.AddField(
            model_name='definition',
            name='used_definitions',
            field=models.ManyToManyField(blank=True, through='definitions.DefinitionUsage', to='definitions.definition', verbose_name='Использованные определения'),
        ),
    ]
