# Generated by Django 5.0.1 on 2024-01-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0002_definition_emoji_alter_definition_description_math'),
    ]

    operations = [
        migrations.AddField(
            model_name='definitionusage',
            name='basis',
            field=models.IntegerField(default=0, verbose_name='Основание'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='is_initial',
            field=models.BooleanField(default=False, verbose_name='Исх.'),
        ),
    ]
