# Generated by Django 5.0.1 on 2024-01-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0003_definitionusage_basis_alter_definition_is_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionLearningProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('show_counter', models.IntegerField(default=0, verbose_name='Показов')),
                ('choose_right_answer_counter', models.IntegerField(default=0, verbose_name='Правильно выбрано')),
                ('write_right_answer_counter', models.IntegerField(default=0, verbose_name='Правильно написано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_process', to='definitions.client', verbose_name='Клиент')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='definitions.definition', verbose_name='Определение')),
            ],
            options={
                'verbose_name': 'Изучаемые определения',
                'verbose_name_plural': 'Изучаемые определения',
            },
        ),
        migrations.CreateModel(
            name='LearnedDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Выучено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learned_definitions', to='definitions.client', verbose_name='Клиент')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='definitions.definition', verbose_name='Определение')),
            ],
            options={
                'verbose_name': 'Выученные определения',
                'verbose_name_plural': 'Выученные определения',
            },
        ),
    ]
