# Generated by Django 5.0.1 on 2024-01-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0004_definitionlearningprocess_learneddefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='symbol',
            field=models.CharField(blank=True, max_length=40, verbose_name='Символ'),
        ),
    ]
