# Generated by Django 5.0.1 on 2024-01-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0006_definition_emoji_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='similar_definition_for', to='definitions.definition', verbose_name='Определение')),
                ('similar_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='similar_definition', to='definitions.definition', verbose_name='Похожее определение')),
            ],
            options={
                'verbose_name': 'Похожее определение',
                'verbose_name_plural': 'Похожиe определения',
            },
        ),
        migrations.AddField(
            model_name='definition',
            name='similar_definitions',
            field=models.ManyToManyField(blank=True, through='definitions.DefinitionSimilarity', to='definitions.definition', verbose_name='Похожие определения'),
        ),
    ]
