# Generated by Django 5.0.1 on 2024-01-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0007_definitionsimilarity_definition_similar_definitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definitionlearningprocess',
            name='choose_right_answer_counter',
        ),
        migrations.RemoveField(
            model_name='definitionlearningprocess',
            name='show_counter',
        ),
        migrations.RemoveField(
            model_name='definitionlearningprocess',
            name='write_right_answer_counter',
        ),
        migrations.AddField(
            model_name='definitionlearningprocess',
            name='action',
            field=models.CharField(choices=[('selection', 'выбор'), ('typing', 'ввод')], default='selection', max_length=20, verbose_name='Действие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='definitionlearningprocess',
            name='score',
            field=models.FloatField(default=0, verbose_name='Баллы'),
        ),
    ]
