# Generated by Django 5.0.1 on 2024-01-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0008_remove_definitionlearningprocess_choose_right_answer_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='proof',
            field=models.TextField(blank=True, default='', verbose_name='Доказательство'),
        ),
    ]
