# Generated by Django 5.0.1 on 2024-01-09 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0009_definition_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learneddefinition',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning', to='definitions.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='learneddefinition',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning', to='definitions.definition', verbose_name='Определение'),
        ),
    ]
