# Generated by Django 5.0.1 on 2024-01-10 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0012_definitionlearningprocess_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField(verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mistakes', to='definitions.client', verbose_name='Клиент')),
                ('definition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mistakes', to='definitions.definition', verbose_name='Определение')),
            ],
            options={
                'verbose_name': 'Ошибка',
                'verbose_name_plural': 'Ошибки',
            },
        ),
    ]
